name: Publish Backend to Docker Hub

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build_and_push:
    name: Build and Push Backend to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ variables.DOCKER_USERNAME }}
          password: ${{ variables.DOCKER_PASSWORD }}
      
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ variables.DOCKER_USERNAME }}/foodgram-backend:latest
            ${{ variables.DOCKER_USERNAME }}/foodgram-backend:${{ github.sha }}